server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://chanadb.ckjts69ujy0u.ap-northeast-2.rds.amazonaws.com/test?autoReconnect=true # 변경해주세요
    username: admin
    password: temppass
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전